package com.be_ai_learning_platform.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * OTP session for email verification during REGISTER flow.
 *
 * Notes:
 * - Store OTP as HMAC hash (never store plain OTP)
 * - Enforce expiry, resend cooldown, and max attempts to reduce spam/bruteforce
 */
@Entity
@Table(name = "email_otp_session", indexes = {
        @Index(name = "idx_email_otp_email", columnList = "email"),
        @Index(name = "idx_email_otp_expires", columnList = "expiresAt")
})
@Data
@NoArgsConstructor
public class EmailOtpSession {

    @Id
    @Column(length = 40)
    private String id; // UUID string, generated by service

    @Column(nullable = false, length = 150)
    private String email;

    @Column(nullable = false, length = 128)
    private String otpHash; // HMAC-SHA256 hex

    @Column(nullable = false)
    private LocalDateTime expiresAt;

    @Column(nullable = false)
    private int attempts = 0;

    @Column(nullable = false)
    private int resendCount = 0;

    @Column(nullable = false)
    private LocalDateTime lastSentAt;

    private LocalDateTime verifiedAt;

    private LocalDateTime consumedAt;

    @Column(nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    public boolean isExpired() {
        return expiresAt != null && expiresAt.isBefore(LocalDateTime.now());
    }

    public boolean isVerified() {
        return verifiedAt != null;
    }

    public boolean isConsumed() {
        return consumedAt != null;
    }
}
